# Generated by Django 5.0.1 on 2024-05-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0003_alter_dossiers_date_trans_dgcmef'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiers',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='date_retour_sign',
            field=models.DateField(blank=True, null=True, verbose_name='Date retour'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='date_trans_dgcmef',
            field=models.DateField(blank=True, null=True, verbose_name='Date retour la DGCMEF'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='date_trans_sign',
            field=models.DateField(blank=True, null=True, verbose_name='Date envois pour signature'),
        ),
    ]
