# Generated by Django 5.0.1 on 2024-05-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0004_dossiers_fichier_alter_dossiers_date_retour_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiers',
            name='date_retour_dgcmef',
            field=models.DateField(blank=True, null=True, verbose_name='Date retour la DGCMEF'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='date_trans_dgcmef',
            field=models.DateField(blank=True, null=True, verbose_name='Date de tensmission à la DGCMEF'),
        ),
    ]
