# Generated by Django 5.0.1 on 2024-05-06 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0005_dossiers_date_retour_dgcmef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='dossier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.dossiers', verbose_name='Dossier'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='intitule_lot',
            field=models.TextField(blank=True, null=True, verbose_name='Intitulé du lot'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='montant_lot',
            field=models.IntegerField(blank=True, null=True, verbose_name='Montant du lot'),
        ),
        migrations.AlterField(
            model_name='lots',
            name='num_lot',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero du lot'),
        ),
    ]
