# Generated by Django 5.0.1 on 2024-05-09 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0006_alter_lots_dossier_id_alter_lots_intitule_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_four', models.CharField(blank=True, max_length=200, null=True)),
                ('rccm', models.CharField(blank=True, max_length=200, null=True)),
                ('ifu', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone1', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('domaine', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='uploads/dao'),
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_publi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Numero de publication')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envois")),
                ('date_publi', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='uploads/avis', verbose_name='Avis de publication')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('dossier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.dossiers', verbose_name='Dossier')),
            ],
        ),
    ]
