# Generated by Django 5.0.1 on 2024-05-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0007_fournisseurs_alter_dossiers_fichier_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='avis',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
