# Generated by Django 5.0.1 on 2024-07-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0009_offres'),
    ]

    operations = [
        migrations.AddField(
            model_name='offres',
            name='date_prevu_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date prévue de réception des offres'),
        ),
        migrations.AddField(
            model_name='offres',
            name='date_reel_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Date réelle de réception des offres'),
        ),
        migrations.AddField(
            model_name='offres',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='offres',
            name='offre_technique',
            field=models.FileField(blank=True, null=True, upload_to='uploads/offres_techniques/', verbose_name='Offre technique'),
        ),
        migrations.AlterField(
            model_name='dossiers',
            name='date_trans_dgcmef',
            field=models.DateField(blank=True, null=True, verbose_name='Date de transmission à la DGCMEF'),
        ),
        migrations.CreateModel(
            name='Marches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_doss_id', models.IntegerField(blank=True, null=True)),
                ('lot_id', models.IntegerField(blank=True, null=True)),
                ('num_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('objet', models.CharField(blank=True, max_length=255, null=True)),
                ('date_appro', models.CharField(blank=True, max_length=100, null=True)),
                ('date_notif', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.IntegerField(blank=True, null=True)),
                ('devise', models.CharField(blank=True, max_length=10, null=True)),
                ('taxe', models.CharField(blank=True, max_length=10, null=True)),
                ('montant2', models.IntegerField(blank=True, null=True)),
                ('devise2', models.CharField(blank=True, max_length=10, null=True)),
                ('taxe2', models.CharField(blank=True, max_length=10, null=True)),
                ('montant3', models.IntegerField(blank=True, null=True)),
                ('devise3', models.CharField(blank=True, max_length=10, null=True)),
                ('taxe3', models.CharField(blank=True, max_length=10, null=True)),
                ('montant4', models.IntegerField(blank=True, null=True)),
                ('devise4', models.CharField(blank=True, max_length=10, null=True)),
                ('taxe4', models.CharField(blank=True, max_length=10, null=True)),
                ('montant_total', models.IntegerField(blank=True, null=True)),
                ('devise_total', models.CharField(blank=True, max_length=10, null=True)),
                ('taxe_total', models.CharField(blank=True, max_length=10, null=True)),
                ('delai', models.CharField(blank=True, max_length=100, null=True)),
                ('attributaire', models.IntegerField(blank=True, null=True)),
                ('date_rem_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('date_retour_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('date_rem_enr', models.CharField(blank=True, max_length=100, null=True)),
                ('date_retour_enr', models.CharField(blank=True, max_length=100, null=True)),
                ('marche', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('dossier_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.dossiers', verbose_name='Dossier')),
            ],
        ),
    ]
