# Generated by Django 5.0.1 on 2024-07-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0010_offres_date_prevu_reception_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_id', models.IntegerField(blank=True, null=True)),
                ('date_par_res', models.CharField(blank=True, max_length=100, null=True)),
                ('num_par_res', models.CharField(blank=True, max_length=100, null=True)),
                ('attributaire', models.CharField(blank=True, max_length=255, null=True)),
                ('litige', models.CharField(blank=True, max_length=255, null=True)),
                ('fichierpub', models.CharField(blank=True, max_length=255, null=True)),
                ('fichierlitige', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('date_prevu_pub', models.DateField(blank=True, null=True)),
                ('date_reelle_pub', models.DateField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, choices=[('Retenu', 'Retenu'), ('Non Retenu', 'Non Retenu')], max_length=10, null=True)),
            ],
        ),
    ]
