# Generated by Django 5.0.1 on 2024-07-17 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0012_resultats_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='marches',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.offres', verbose_name='Offre'),
        ),
    ]
