# Generated by Django 5.0.1 on 2024-07-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0013_marches_offre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marches',
            old_name='dossier_id',
            new_name='dossier',
        ),
    ]
