# Generated by Django 5.0.1 on 2024-07-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0014_rename_dossier_id_marches_dossier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marches',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
