# Generated by Django 5.0.1 on 2024-07-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0016_remove_marches_date_appro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marches',
            name='date_appro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='date_rem_enr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='date_rem_sign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='date_retour_enr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='delai',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='devise',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='devise2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='devise3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='devise4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='devise_total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='lot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='mar_doss_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='marche',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='montant2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='montant3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='montant4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='montant_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='objet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='taxe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='taxe2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='taxe3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='taxe4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marches',
            name='taxe_total',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='marches',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.offres'),
        ),
    ]
