# Generated by Django 5.0.1 on 2024-07-22 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0017_marches_date_appro_marches_date_rem_enr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marches',
            name='date_appro',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='date_rem_enr',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='date_rem_sign',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='date_retour_enr',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='delai',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='devise2',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='devise3',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='devise4',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='devise_total',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='lot_id',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='mar_doss_id',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='marche',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='montant2',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='montant3',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='montant4',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='montant_total',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='objet',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='taxe',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='taxe2',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='taxe3',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='taxe4',
        ),
        migrations.RemoveField(
            model_name='marches',
            name='taxe_total',
        ),
        migrations.AlterField(
            model_name='marches',
            name='offre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.offres', verbose_name='Offre'),
        ),
    ]
