# Generated by Django 5.0.1 on 2024-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0019_offres_lots'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='date_lancement_pulication',
            field=models.DateField(blank=True, null=True, verbose_name='Date de lancement de publication'),
        ),
    ]
