# Generated by Django 5.0.1 on 2024-07-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0022_lots_marche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offres',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.fournisseurs', verbose_name='Entreprise'),
        ),
    ]
