# Generated by Django 5.0.1 on 2024-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0023_alter_offres_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offres',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entreprise'),
        ),
    ]
