# Generated by Django 5.0.1 on 2024-07-27 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0024_alter_offres_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='offres',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='suivi.fournisseurs'),
        ),
    ]
