# Generated by Django 5.0.1 on 2024-07-29 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0027_alter_marches_attributaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='marches',
            name='resultat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.resultats', verbose_name='Résultat'),
        ),
    ]
