# Generated by Django 5.0.1 on 2024-07-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0028_marches_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultats',
            name='attributaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultats', to='suivi.fournisseurs'),
        ),
    ]
