# Generated by Django 5.0.1 on 2024-07-30 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0029_alter_resultats_attributaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marches',
            name='attributaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marches', to='suivi.fournisseurs'),
        ),
    ]
