# Generated by Django 5.0.1 on 2024-07-31 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0030_alter_marches_attributaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offres',
            name='lot_id',
        ),
        migrations.RemoveField(
            model_name='offres',
            name='lots',
        ),
        migrations.AddField(
            model_name='offres',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suivi.lots', verbose_name='Lot'),
        ),
    ]
