# Generated by Django 5.0.1 on 2024-08-07 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0034_remove_resultats_fichierlitige_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultats',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='suivi.lots'),
        ),
    ]
