# Generated by Django 5.0.1 on 2024-08-13 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi', '0035_alter_resultats_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitems',
            name='budget_travaux',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='centre_cout',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='composante',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_demarrage',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_dgcmef',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_dgcmef_reel',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_off',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_off_reel',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_reel_demarrage',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_reel_fin',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_resultat',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_tech',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_tech_reel',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='date_visite_site',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='delai_exe',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='delai_reel_exe',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='immobilisation',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='montant_dispo',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='montant_estime',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='nbr_lot',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='plan_id',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='projet',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='resultat',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='temp_reel',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='typcredit',
        ),
        migrations.RemoveField(
            model_name='planitems',
            name='type',
        ),
        migrations.AddField(
            model_name='planitems',
            name='agent_charge_dossier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='annee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suivi.plans'),
        ),
        migrations.AddField(
            model_name='planitems',
            name='contentieux_litiges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='convocation_analyses_offres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='convocation_ouverture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_demarrage_prevue_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_effectives_analyses_offres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_emission_ordre_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_introduction_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_notification_projet_contrat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_prevue_lancement_dgcmef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_prevue_reception_dossier_technique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_prevue_remise_offres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_reelle_demarrage_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_reelle_lancement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_reelle_lancement_dgcmef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_reelle_reception_dossier_technique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_reelle_remise_offres',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_remise_garantie_bonne_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_remise_site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_retour_enregistrement_contrat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_retour_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_retour_signature_dg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_signature_contrat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_transmission_contrat_enregistrement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_transmission_dgcmef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_transmission_par_dgcmef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='date_transmission_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='delai_prevue_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='delai_reelle_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='direction_charge_dossier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='disponible',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='dossiers_lances_non_encore_attribues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='dossiers_marches_non_conclu_montant_alloue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='dossiers_non_lances_montant_alloue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='dossiers_non_recus_montant_alloue',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='dossiers_recus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='duree_reelle_evaluation_offres_jours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='elements_composantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='execution_ppm_2023_30_septembre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='gestionnaire_credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='intitule_dossier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='marches_en_cours_execution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='marches_executes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='mode_passation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='montant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='montant_depenses_engagees_non_liquidees',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='montant_inscription_budgetaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nature_prestations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nom_attributaire_provisoire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nombre_dossiers_lances',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nombre_dossiers_recus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nombre_ligne_fait_objet_marche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nombre_marches_conclure_par_ligne_ppm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='nombre_marches_conclus_par_ligne_ppm',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='num_credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='numero_marche',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='observations_eventuelles_dgcmef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='observations_suivi_quotidien_04_12_2023',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='publication_dgcmef',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='ref_dossier_appel_concurrence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='reference_publication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='retour_signature_pv',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='service_charge_dossier_technique',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='taux_lancement_dossiers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='taux_passation_marches',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='taux_reception_dossiers_dmp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='temps_necessaire_evaluation_offres_jours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='transmission_dgcmef_eventuel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='transmission_pv_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='type_prestation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='types',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitems',
            name='unite_service_beneficiaire',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planitems',
            name='agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='planitems',
            name='budget',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planitems',
            name='date_butoir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planitems',
            name='num_ordre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
